### PR TITLE
skip empty dropdown menu generation - fix #188

### LINKED ISSUE #188: Remove menu group when there is no items inside
Top menu can have group of items. If all of them are forbidden to currently logged user empty group stays in menu. Group should be removed if it have no items inside.

### PR DESCRIPTION
**Pull request by JarekW**

### CODE REVIEW

**Comment by szymach** [comment]
:+1:

**Comment by JarekW** [comment]
@fsi-open

**Comment by chives** [comment]
:+1:

**Comment by JarekW** [comment]
@fsi-open

**Comment by JarekW** [comment]
I mark it as [WIP] to prevent merging it. In discussion about this pull came up some doubts:
* is this necessary, because it structure of menu in yml does'nt corresponds to actual menu. Thus must be some listener in developer application that removes empty groups.
* placement of checking empty items. Maybe better to check it during yaml parsing

Some solution to this problem are necessary, so please comment. @fsi-open

**Comment by JarekW** [comment]
@fsi-open

**Comment by JarekW** [comment]
@fsi-open

**Comment by JarekW** [comment]
@fsi-open

**Comment by chives** [comment]
Some listener with low priority (called at last) which removes empty menus is the best approach in my opinion

**Comment by JarekW** [comment]
you mean in application that use admin-bundle or in admin bundle?

**Comment by chives** [comment]
@JarekW in admin-bundle

**Comment by JarekW** [comment]
@fsi-open changed

**Comment by szymach** [comment]
:+1:

**Comment by chives** [comment]
:+1:

**Comment by JarekW** [comment]
@fsi-open

**Comment by JarekW** [comment]
@rno :)

**Comment by JarekW** [comment]
@rn0

**Comment by rn0** [comment]
:+1:

**Pull request merged**
