### PR TITLE
Add compiler pass for setting event dispatcher

### PR DESCRIPTION
**Pull request by szymach**

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@rn0

**Comment by szymach** [comment]
@rn0

**Comment by szymach** [comment]
@rn0 @rn0 @rn0 @rn0 @rn0 @rn0 @rn0 @rn0 @rn0 @rn0

**Comment by norzechowicz** [comment]
this PR is mentioned to be merged only to `2.1` branch?

**Comment by szymach** [comment]
@rn0 

@norzechowicz  Yes, after talking with @chives we agreed to only push minor fixes to 2.0 branch and new things to 2.1 (and this is hardly a fix, just an improvement). After this gets merged into 2.1, I will also update the master branch

**Pull request merged**
