### PR TITLE
Allow to specify translation domain for batch actions

### PR DESCRIPTION
**Pull request by rn0**
datagrid_definition.yml:
```yml
columns:
  batch:
    type: batch
    options:
      translation_domain: FSiAdminSecurity
      actions:
        delete:
          route_name: fsi_admin_batch
          additional_parameters: { element: admin_user }
```

### CODE REVIEW

**Comment by rn0** [comment]
@fsi-open

**Comment by szymach** [comment]
:+1:

**Comment by JarekW** [comment]
:+1:

**Comment by chives** [comment]
:+1:

**Pull request merged**
