### PR TITLE
Fixed README status and documentation links, added new ones

### PR DESCRIPTION
**Pull request by szymach**

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open

**Comment by JarekW** [comment]
maybe same content of config [as before](https://scrutinizer-ci.com/g/fsi-open/admin-bundle/inspections/cc3e543f-181c-4d95-97d0-54c4a7e35bfa/configs) (I guess it exclude checks of vendor?)
```yml
filter:
    excluded_paths: [vendor/*, app/*, web/*]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
```

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@rn0 @JarekW

**Pull request merged**
